name: Quality Gate

on: pull_request

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Load test credentials
        run: |
          echo "const apiKey = '';" > test/test_config.dart
          echo "const projectId = '';" >> test/test_config.dart
          echo "const email = '';" >> test/test_config.dart
          echo "const password = '';" >> test/test_config.dart

      - name: Verify code formatting
        run: dart format --set-exit-if-changed .
      - name: Get dependencies
        run: pub get
      - name: Static code analysis
        run: dart analyze --fatal-infos
